[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/build/manifest.json"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
numReplicas = 1
region = "us-west2"
